import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding Cera\'s Workshop actual inventory...')

  // First, delete ALL existing categories and products to ensure clean slate
  console.log('Cleaning existing data...')
  await prisma.productImage.deleteMany({})
  await prisma.product.deleteMany({})
  await prisma.category.deleteMany({})

  console.log('Creating fresh categories...')
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'amigurumi' },
      update: {},
      create: {
        name: 'Amigurumi',
        description: 'Adorable stuffed animals, creatures, and characters',
        slug: 'amigurumi',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'keychains' },
      update: {},
      create: {
        name: 'Keychains',
        description: 'Cute mini plushies for your keys and bags',
        slug: 'keychains',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'accessories' },
      update: {},
      create: {
        name: 'Accessories',
        description: 'Wearable items and functional pieces',
        slug: 'accessories',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'home-decor' },
      update: {},
      create: {
        name: 'Home Decor',
        description: 'Decorative items for your home',
        slug: 'home-decor',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'seasonal' },
      update: {},
      create: {
        name: 'Seasonal',
        description: 'Holiday and seasonal themed items',
        slug: 'seasonal',
      },
    }),
  ])

  // Your actual inventory with detailed crochet specifications
  const products = [
    // Fat Animal Series
    {
      name: 'Fat Husky',
      slug: 'fat-husky',
      yarn: 'Plush yarn',
      yarnGrams: 120,
      yarnCost: 7.20,
      polyfilGrams: 80,
      polyfilCost: 2.40,
      eyesUsed: '12mm Safety Eyes (Black)',
      eyesCost: 0.85,
      hookSize: '5.0mm (H/8)',
      timeMinutes: 360, // 6 hours
      laborWage: 36.00,
      calculatedPrice: 46.45,
      salePrice: 35.00,
      profitMargin: -24.65, // Underpriced - labor of love!
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id, // Amigurumi
      featured: true,
    },
    {
      name: 'Fat Poodle',
      slug: 'fat-poodle',
      yarn: 'Plush yarn',
      yarnGrams: 90,
      yarnCost: 4.50,
      polyfilGrams: 60,
      polyfilCost: 1.80,
      eyesUsed: '10mm Safety Eyes (Black)',
      eyesCost: 0.75,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 240, // 4 hours
      laborWage: 24.00,
      calculatedPrice: 31.05,
      salePrice: 25.00,
      profitMargin: -19.48,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: true,
    },
    {
      name: 'Fat Pug',
      slug: 'fat-pug',
      yarn: 'Plush yarn',
      yarnGrams: 85,
      yarnCost: 2.55,
      polyfilGrams: 55,
      polyfilCost: 1.65,
      eyesUsed: '10mm Safety Eyes (Black)',
      eyesCost: 0.75,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 240,
      laborWage: 24.00,
      calculatedPrice: 28.95,
      salePrice: 25.00,
      profitMargin: -13.66,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: false,
    },
    {
      name: 'Fat Shiba',
      slug: 'fat-shiba',
      yarn: 'Plush yarn',
      yarnGrams: 85,
      yarnCost: 4.25,
      polyfilGrams: 55,
      polyfilCost: 1.65,
      eyesUsed: '10mm Safety Eyes (Black)',
      eyesCost: 0.75,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 240,
      laborWage: 24.00,
      calculatedPrice: 30.65,
      salePrice: 25.00,
      profitMargin: -18.47,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: false,
    },

    // Small Plushies & Fidgets
    {
      name: 'Pickles',
      slug: 'pickles',
      yarn: 'Plush yarn',
      yarnGrams: 25,
      yarnCost: 1.00,
      polyfilGrams: 15,
      polyfilCost: 0.45,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 45,
      laborWage: 4.50,
      calculatedPrice: 5.95,
      salePrice: 7.00,
      profitMargin: 17.65,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id, // Amigurumi (moved from fidget toys)
      featured: false,
    },
    {
      name: 'Gummy Bears',
      slug: 'gummy-bears',
      yarn: 'Plush yarn',
      yarnGrams: 20,
      yarnCost: 0.60,
      polyfilGrams: 12,
      polyfilCost: 0.36,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '3.5mm (E/4)',
      timeMinutes: 30,
      laborWage: 3.00,
      calculatedPrice: 3.96,
      salePrice: 7.00,
      profitMargin: 76.77,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id, // Amigurumi (moved from fidget toys)
      featured: false,
    },

    // Keychains
    {
      name: 'Gummy Bear Keychains',
      slug: 'gummy-bear-keychains',
      yarn: 'Plush yarn',
      yarnGrams: 8,
      yarnCost: 0.24,
      polyfilGrams: 5,
      polyfilCost: 0.15,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '3.5mm (E/4)',
      timeMinutes: 20,
      laborWage: 2.00,
      calculatedPrice: 2.39,
      salePrice: 5.00,
      profitMargin: 109.21,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[1].id, // Keychains
      featured: false,
    },
    {
      name: 'Pickle Keychains',
      slug: 'pickle-keychains',
      yarn: 'Lily Sugar \'n Cream (Sage Green)',
      yarnGrams: 10,
      yarnCost: 0.40,
      polyfilGrams: 6,
      polyfilCost: 0.18,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 25,
      laborWage: 2.50,
      calculatedPrice: 3.08,
      salePrice: 7.00,
      profitMargin: 127.27,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[1].id,
      featured: false,
    },
    {
      name: 'Mushroom Keychain',
      slug: 'mushroom-keychain',
      yarn: 'Red Heart Super Saver (White/Red)',
      yarnGrams: 12,
      yarnCost: 0.36,
      polyfilGrams: 8,
      polyfilCost: 0.24,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 30,
      laborWage: 3.00,
      calculatedPrice: 3.60,
      salePrice: 5.00,
      profitMargin: 38.89,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[1].id,
      featured: false,
    },
    {
      name: 'Sunflower Keychain',
      slug: 'sunflower-keychain',
      yarn: 'Lion Brand Vanna\'s Choice (Yellow/Brown)',
      yarnGrams: 15,
      yarnCost: 0.75,
      polyfilGrams: 8,
      polyfilCost: 0.24,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 35,
      laborWage: 3.50,
      calculatedPrice: 4.49,
      salePrice: 7.00,
      profitMargin: 55.90,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[1].id,
      featured: false,
    },

    // Animals & Creatures
    {
      name: 'Snakes',
      slug: 'snakes',
      yarn: 'Red Heart Super Saver (Green)',
      yarnGrams: 40,
      yarnCost: 1.20,
      polyfilGrams: 25,
      polyfilCost: 0.75,
      eyesUsed: '6mm Safety Eyes (Black)',
      eyesCost: 0.50,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 90,
      laborWage: 9.00,
      calculatedPrice: 11.45,
      salePrice: 20.00,
      profitMargin: 74.67,
      status: 'in_stock',
      image: '/Product Images/Snake (beetlejuice sandworm).png',
      categoryId: categories[0].id, // Amigurumi (moved from fidget toys)
      featured: false,
    },
    {
      name: 'Mushrooms',
      slug: 'mushrooms',
      yarn: 'Plush yarn',
      yarnGrams: 35,
      yarnCost: 1.75,
      polyfilGrams: 25,
      polyfilCost: 0.75,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 60,
      laborWage: 6.00,
      calculatedPrice: 8.50,
      salePrice: 10.00,
      profitMargin: 17.65,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: false,
    },
    {
      name: 'Cow',
      slug: 'cow',
      yarn: 'Plush yarn',
      yarnGrams: 70,
      yarnCost: 2.10,
      polyfilGrams: 45,
      polyfilCost: 1.35,
      eyesUsed: '10mm Safety Eyes (Black)',
      eyesCost: 0.75,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 180,
      laborWage: 18.00,
      calculatedPrice: 22.20,
      salePrice: 20.00,
      profitMargin: -9.91,
      status: 'in_stock',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: false,
    },
    {
      name: 'Dolphin',
      slug: 'dolphin',
      yarn: 'Plush yarn',
      yarnGrams: 150,
      yarnCost: 9.00,
      polyfilGrams: 100,
      polyfilCost: 3.00,
      eyesUsed: '12mm Safety Eyes (Black)',
      eyesCost: 0.85,
      hookSize: '5.0mm (H/8)',
      timeMinutes: 420, // 7 hours
      laborWage: 42.00,
      calculatedPrice: 54.85,
      salePrice: 45.00,
      profitMargin: -17.93,
      status: 'made_to_order',
      image: '/images-coming-soon.svg',
      categoryId: categories[0].id,
      featured: true,
    },
    {
      name: 'Loaf Cat',
      slug: 'loaf-cat',
      yarn: 'Plush yarn',
      yarnGrams: 50,
      yarnCost: 2.50,
      polyfilGrams: 30,
      polyfilCost: 0.90,
      eyesUsed: '8mm Safety Eyes (Green)',
      eyesCost: 0.60,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 120,
      laborWage: 12.00,
      calculatedPrice: 16.00,
      salePrice: 15.00,
      profitMargin: -6.25,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/loaf-cat.jpg',
      categoryId: categories[0].id,
      featured: false,
    },
    {
      name: 'Bee',
      slug: 'bee',
      yarn: 'Plush yarn',
      yarnGrams: 40,
      yarnCost: 1.20,
      polyfilGrams: 25,
      polyfilCost: 0.75,
      eyesUsed: '8mm Safety Eyes (Black)',
      eyesCost: 0.60,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 90,
      laborWage: 9.00,
      calculatedPrice: 11.55,
      salePrice: 15.00,
      profitMargin: 29.87,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/bee.jpg',
      categoryId: categories[0].id,
      featured: false,
    },
    {
      name: 'Turtle',
      slug: 'turtle',
      yarn: 'Plush yarn',
      yarnGrams: 45,
      yarnCost: 2.25,
      polyfilGrams: 30,
      polyfilCost: 0.90,
      eyesUsed: '8mm Safety Eyes (Black)',
      eyesCost: 0.60,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 105,
      laborWage: 10.50,
      calculatedPrice: 14.25,
      salePrice: 15.00,
      profitMargin: 5.26,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/turtle.jpg',
      categoryId: categories[0].id,
      featured: false,
    },

    // Accessories
    {
      name: 'Star bag',
      slug: 'star-bag',
      yarn: 'Lion Brand Vanna\'s Choice (Gold)',
      yarnGrams: 200,
      yarnCost: 10.00,
      polyfilGrams: 0,
      polyfilCost: 0.00,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '5.5mm (I/9)',
      timeMinutes: 300, // 5 hours
      laborWage: 30.00,
      calculatedPrice: 40.00,
      salePrice: 40.00,
      profitMargin: 0.00,
      status: 'made_to_order',
      image: '/images-coming-soon.svg', // was '/products/star-bag.jpg',
      categoryId: categories[2].id, // Accessories
      featured: true,
    },
    {
      name: 'Sunflower Coaster',
      slug: 'sunflower-coaster',
      yarn: 'Lily Sugar \'n Cream (Yellow/Brown)',
      yarnGrams: 20,
      yarnCost: 0.80,
      polyfilGrams: 0,
      polyfilCost: 0.00,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 30,
      laborWage: 3.00,
      calculatedPrice: 3.80,
      salePrice: 7.00,
      profitMargin: 84.21,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/sunflower-coaster.jpg',
      categoryId: categories[3].id, // Home Decor category
      featured: false,
    },
    {
      name: 'Worsted Bandana',
      slug: 'worsted-bandana',
      yarn: 'Lion Brand Vanna\'s Choice (Various Colors)',
      yarnGrams: 120,
      yarnCost: 6.00,
      polyfilGrams: 0,
      polyfilCost: 0.00,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '5.0mm (H/8)',
      timeMinutes: 180,
      laborWage: 18.00,
      calculatedPrice: 24.00,
      salePrice: 30.00,
      profitMargin: 25.00,
      status: 'made_to_order',
      image: '/Product Images/Bandana.png',
      categoryId: categories[2].id,
      featured: false,
    },
    {
      name: 'Light Weight Bandana',
      slug: 'light-weight-bandana',
      yarn: 'Bernat Cotton (Various Colors)',
      yarnGrams: 80,
      yarnCost: 4.80,
      polyfilGrams: 0,
      polyfilCost: 0.00,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 150,
      laborWage: 15.00,
      calculatedPrice: 19.80,
      salePrice: 30.00,
      profitMargin: 51.52,
      status: 'made_to_order',
      image: '/Product Images/Bandana2.png',
      categoryId: categories[2].id,
      featured: false,
    },

    // Seasonal Items
    {
      name: 'Ghost S',
      slug: 'ghost-s',
      yarn: 'Red Heart Super Saver (White)',
      yarnGrams: 30,
      yarnCost: 0.90,
      polyfilGrams: 20,
      polyfilCost: 0.60,
      eyesUsed: '6mm Safety Eyes (Black)',
      eyesCost: 0.50,
      hookSize: '4.0mm (F/6)',
      timeMinutes: 45,
      laborWage: 4.50,
      calculatedPrice: 6.50,
      salePrice: 10.00,
      profitMargin: 53.85,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/ghost-s.jpg',
      categoryId: categories[4].id, // Seasonal (was categories[3])
      featured: false,
    },
    {
      name: 'Ghost L',
      slug: 'ghost-l',
      yarn: 'Red Heart Super Saver (White)',
      yarnGrams: 50,
      yarnCost: 1.50,
      polyfilGrams: 35,
      polyfilCost: 1.05,
      eyesUsed: '8mm Safety Eyes (Black)',
      eyesCost: 0.60,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 75,
      laborWage: 7.50,
      calculatedPrice: 10.65,
      salePrice: 15.00,
      profitMargin: 40.85,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/ghost-l.jpg',
      categoryId: categories[4].id,
      featured: false,
    },
    {
      name: 'Pumpkin Spinner',
      slug: 'pumpkin-spinner',
      yarn: 'Lion Brand Vanna\'s Choice (Pumpkin)',
      yarnGrams: 45,
      yarnCost: 2.25,
      polyfilGrams: 25,
      polyfilCost: 0.75,
      eyesUsed: 'None',
      eyesCost: 0.00,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 90,
      laborWage: 9.00,
      calculatedPrice: 12.00,
      salePrice: 15.00,
      profitMargin: 25.00,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/pumpkin-spinner.jpg',
      categoryId: categories[4].id,
      featured: false,
    },
    {
      name: 'Chibi Grim Reaper',
      slug: 'chibi-grim-reaper',
      yarn: 'Red Heart Super Saver (Black/White)',
      yarnGrams: 60,
      yarnCost: 1.80,
      polyfilGrams: 40,
      polyfilCost: 1.20,
      eyesUsed: '8mm Safety Eyes (Red)',
      eyesCost: 0.60,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 150,
      laborWage: 15.00,
      calculatedPrice: 18.60,
      salePrice: 20.00,
      profitMargin: 7.53,
      status: 'in_stock',
      image: '/images-coming-soon.svg', // was '/products/chibi-grim-reaper.jpg',
      categoryId: categories[4].id,
      featured: false,
    },
    {
      name: 'Spood',
      slug: 'spood',
      yarn: 'Red Heart Super Saver (Black)',
      yarnGrams: 55,
      yarnCost: 1.65,
      polyfilGrams: 35,
      polyfilCost: 1.05,
      eyesUsed: '8mm Safety Eyes (Black)',
      eyesCost: 0.60,
      hookSize: '4.5mm (G/7)',
      timeMinutes: 120,
      laborWage: 12.00,
      calculatedPrice: 15.30,
      salePrice: 20.00,
      profitMargin: 30.72,
      status: 'in_stock',
      image: '/Product Images/Spooky Spiders.png',
      categoryId: categories[4].id,
      featured: false,
    },
    {
      name: 'Sam Halloween',
      slug: 'sam-halloween',
      yarn: 'Red Heart Super Saver (Orange/Brown)',
      yarnGrams: 100,
      yarnCost: 3.00,
      polyfilGrams: 70,
      polyfilCost: 2.10,
      eyesUsed: '10mm Safety Eyes (Black)',
      eyesCost: 0.75,
      hookSize: '5.0mm (H/8)',
      timeMinutes: 300, // 5 hours
      laborWage: 30.00,
      calculatedPrice: 35.85,
      salePrice: 35.00,
      profitMargin: -2.37,
      status: 'made_to_order',
      image: '/Product Images/Sam.png',
      categoryId: categories[4].id,
      featured: true,
    },
  ]

  // Clear existing products first
  await prisma.product.deleteMany({})

  // Create products
  const createdProducts = []
  for (const product of products) {
    const created = await prisma.product.create({
      data: product
    })
    createdProducts.push(created)
  }

  // Add additional bandana variation images
  const worstedBandana = createdProducts.find(p => p.slug === 'worsted-bandana')
  const lightWeightBandana = createdProducts.find(p => p.slug === 'light-weight-bandana')

  if (worstedBandana) {
    await prisma.productImage.createMany({
      data: [
        {
          productId: worstedBandana.id,
          url: '/Product Images/Bandana.png',
          alt: 'Worsted Bandana - Main View',
          isPrimary: true,
          order: 0
        },
        {
          productId: worstedBandana.id,
          url: '/Product Images/Bandana3.png',
          alt: 'Worsted Bandana - Variation 1',
          isPrimary: false,
          order: 1
        },
        {
          productId: worstedBandana.id,
          url: '/Product Images/Bandana4.png',
          alt: 'Worsted Bandana - Variation 2',
          isPrimary: false,
          order: 2
        },
        {
          productId: worstedBandana.id,
          url: '/Product Images/Bandana edge.png',
          alt: 'Worsted Bandana - Edge Detail',
          isPrimary: false,
          order: 3
        }
      ]
    })
  }

  if (lightWeightBandana) {
    await prisma.productImage.createMany({
      data: [
        {
          productId: lightWeightBandana.id,
          url: '/Product Images/Bandana2.png',
          alt: 'Light Weight Bandana - Main View',
          isPrimary: true,
          order: 0
        },
        {
          productId: lightWeightBandana.id,
          url: '/Product Images/Bandana5.png',
          alt: 'Light Weight Bandana - Variation 1',
          isPrimary: false,
          order: 1
        },
        {
          productId: lightWeightBandana.id,
          url: '/Product Images/Bandana_Folded.png',
          alt: 'Light Weight Bandana - Folded View',
          isPrimary: false,
          order: 2
        }
      ]
    })
  }

  console.log('✅ Cera\'s Workshop actual inventory seeded successfully!')
  console.log(`Created 5 categories and 27 products (removed out of stock items)`)
  console.log('📸 Added bandana variation images and reorganized categories')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
